name: build-comfy
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { packages: write, contents: read }
    steps:
      - name: Resolve latest ComfyUI SHA
        id: sha
        run: |
          COMFY_SHA=$(git ls-remote https://github.com/comfyanonymous/ComfyUI.git HEAD | cut -f1)
          SHORT=${COMFY_SHA:0:7}
          DATE=$(date +%Y-%m-%d)
          echo "COMFY_SHA=$COMFY_SHA" >> $GITHUB_OUTPUT
          echo "SHORT=$SHORT" >> $GITHUB_OUTPUT
          echo "DATE=$DATE" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: COMFY_SHA=${{ steps.sha.outputs.COMFY_SHA }}
          tags: |
            ghcr.io/${{ github.actor }}/comfy:${{ steps.sha.outputs.DATE }}-${{ steps.sha.outputs.SHORT }}
            ghcr.io/${{ github.actor }}/comfy:stable-${{ steps.sha.outputs.DATE }}
            ghcr.io/${{ github.actor }}/comfy:stable
